### ISSUE TITLE
Expiration TTL always -1

### ISSUE THREAD

**Issue by cmorsucci** [silentbobbert/EFCache.Redis#13]
I do the following like into the tutorial:
```
public class RedisCachingPolicy : CachingPolicy
    {
        protected override void GetExpirationTimeout(ReadOnlyCollection<EntitySetBase> affectedEntitySets, out TimeSpan slidingExpiration, out DateTimeOffset absoluteExpiration)
        {
            slidingExpiration = TimeSpan.FromMinutes(5);
            absoluteExpiration = DateTimeOffset.Now.AddMinutes(30);
        }
    }
```

But the TTL and PTTL always -1 why?
The overriden function was correctly called but has no effect.

**Comment by silentbobbert** [comment]
Hey cmorsucci - the Caching Policy classes on their own are pretty basic. You could override the base class yourself and override the method like I have done above. In fact, you should do that because the defaults of 5 / 30 minutes might not suit your use case.

To get redis caching working you need a Configuration class which inherits DbConfiguration. In the constructor you set up caching, and can supply an instance of the policy:

```
public class Configuration : DbConfiguration
    {
        public static Func<string, string, Exception, bool> LogException;
        public Configuration()
        {
            bool useRedis;
            bool.TryParse(ConfigurationManager.AppSettings["UseRedisCache"], out useRedis);

            if (!useRedis) return;

            RedisCache cache;
            try
            {
                cache = new RedisCache(ConfigurationManager.AppSettings["RedisConnectionString"]);

                cache.CachingFailed += (sender, e) =>
                {
                    if (LogException != null)
                    {
                        LogException("ERROR",
                            string.Format(
                                "An Error Occured caching results with Redis: {0}",
                                e.Message), e);
                    }
                };
            }
            catch (RedisCacheException ex)
            {
                cache = null;
                if (LogException != null)
                {
                    LogException("ERROR", string.Format("A Redis Caching Exception Occured {0}", ex.Message), ex);
                }
                
            }
            catch (Exception ex)
            {
                cache = null;
                if (LogException != null)
                {
                    LogException("ERROR", string.Format("A General Exception Occured {0}", ex.Message), ex);    
                }
            }

            if (cache == null) return;

            var transactionHandler = new CacheTransactionHandler(cache);

            AddInterceptor(transactionHandler);

            Loaded +=
                (sender, args) => args.ReplaceService<DbProviderServices>(
                    (s, _) => new CachingProviderServices(s, transactionHandler, new RedisCachingPolicy()));
        }
    }
```

As you can see - its only on the last line of this sample that an instance of the caching policy class is created.

Does this help?

**Comment by cmorsucci** [comment]
Yes, i follow the how-to pdf like your example, but the TTL still on -1 that means that there is no expiration time.. have you check the TTL on your example?

**Comment by silentbobbert** [comment]
Sorry, but I have not seen this issue, and the other contributors have not reported it either. That's not to say others like yourself are mistaken.

If you have the time, you could clone the EF cache project from http://efcache.codeplex.com/ and my Redis extension project from right here on github and replace the nuget packages with the .net project versions.

That would allow you to step in with your debugger and see what's going on. This could lead you to a problem with your own code/config or point me to a bug in this extension or a bug in the EF cache package.

I don't have enough information from you to investigate further myself.

Sorry

Ian

**Comment by cmorsucci** [comment]
Hi, i have imported the project into mine and i see that in StackExchangeRedisExtensions.cs you do this:

    public static void Set<T>(this IDatabase cache, string key, T value) where T : class
    {
        cache.StringSet(key, Serialize<T>(value));
    }

But StringSet accept expiration time that was used by Redis to expire the cached item.. so why you don't pass that expiration to that method? You use 

    private static bool EntryExpired(CacheEntry entry, DateTimeOffset now)

to manage expiration why not the Redis system?

**Comment by silentbobbert** [comment]
Hi cmorsucci

I was not aware of that optional parameter - perhaps that was added to StackExchange.Redis at some point later or I just missed it.

I'm not sure this helps you with your issue though.

Is your issue that Redis itself retains a kvp even for items considered by the EF caching mechanism as expired? Do you expect expired items to drop out of Redis?

The internal expiration mechanism should work with EF and your application. I can see a problem if something else is sharing your Redis instance perhaps...

I guess there is a chance that RAM in Redis will be consumed by expired items with the current implementation, so its worth looking at Redis' own expiration features.

I will do some research when I get time.

Do you still have an issue or did referencing the projects allow you to solve it?

**Comment by tiwariarvin** [comment]
Hey cmorsucci,

Redis never drops expired items by itself until memory is full. Soon after memory is full Redis will use "maxmemory-policy" for key eviction algorithm.

In my use case I have set it to "allkeys-lru" to remove "expired" keys when memory is full to let new keys get in.

Please refer "eviction policy" section of redis here - http://redis.io/topics/lru-cache. 

Hope this helps.

PS: I am using this library for a production system which runs on approx 400 concurrent users and it looks stable to me.

Cheers
Arvin

**Comment by cmorsucci** [comment]
Ok, tnx for the support, i close the topic ;)

**Comment by tiwariarvin** [comment]
pleasure.
