### ISSUE TITLE
Support database number

### ISSUE THREAD

**Issue by berniezhao** [silentbobbert/EFCache.Redis#14]
Redis supports multiple databases and StackExchange.Redis does support that.  Does it make sense to add a RedisCache constructor that takes database number?  Or let it be part of connection string?
Thank you.

**Comment by silentbobbert** [comment]
Hi berniezhao

StackExchange.Redis does allow you to use an object as well as a string.

```
string configString = GetRedisConfiguration();
var options = ConfigurationOptions.Parse(configString);
options.ClientName = GetAppName(); // only known at runtime
options.AllowAdmin = true;
conn = ConnectionMultiplexer.Connect(options);
```

In this example the "options" object is the result of parsing/deserialising a string.

I will look at implementing something along these lines, so it would be possible to set more advanced options on the connection string like you suggest.

**Comment by silentbobbert** [comment]
@berniezhao I have had a look at this, and I believe you can already achieve what you want using the connection string. You would have to look up StackExchange.Redis for more examples of how to set it up properly. With the string, you should be able to use Twemproxy or add multiple servers as a cluster.

So far, my own use case has limited me to running redis locally, and I have not needed to stretch to more than one db or instance of redis.

I will add a second constructor for RedisCache so you can pass in a pre built options object.

**Comment by silentbobbert** [comment]
@berniezhao I have added the new constructor to RedisCache, and I have published a new NuGet package. It some times takes a little while for NuGet.org to re-index and show up in Visual Studio as an update.

I will close this issue now, if you have any more questions or ideas, please let me know :+1:

**Comment by berniezhao** [comment]
@silentbobbert awesome thanks!  Yes connection string works.  Just for everyone's information, you can use "localhost:6379,defaultDatabase=0" to specify the database.

**Comment by tiwariarvin** [comment]
Thanks silentbobbert and berniezhao, I was about to scale cache and needed this constructor too.
