### ISSUE TITLE
NuGet Dependencies

### ISSUE THREAD

**Issue by crowinsite** [silentbobbert/EFCache.Redis#15]
The project's dependencies are lower than that of the package, as far as I can tell. Second level caching is a product of Entity Framework 6, though I've heard 6.1 is best for this. The others, at least to me, do not act as a barrier to usage.

In my use case, we have a product that is in beta testing and will continue to need the ability to adapt to changes quickly for the near future. Because of this Entity Framework was and is our choice of communication with our database. However, we have quite a few projects already using EF 6.1.0. I would prefer not performing rigorous tests to upgrade to EF 6.1.3. At the same time we do want to implement caching with Redis.

I would prefer not manually using the code found within this repository and loosing track of potential upgrades and fixes. If this is more of a pain than it is worth I understand, either way we look forward to using this package and contributing in the future.

**Comment by silentbobbert** [comment]
Hi Jeremy. I think what you are saying is that if you use the source code version then you can use an older version of EF, but my package forces you to a higher version? 

You may be able to force install my package and disregard the dependencies. 

I think I can adjust the NuGet package to allow a range of versions. The package certainly started life before 6.1.3 so some flexibility should be possible. It will depend on my dependencies. 

Just for info, EF provides L1 cache - usually with IoC this means per request EF will cache all on its own. It will still do that even using my package. My package allows you to gain L2 cache, out of process and shareable across many clients - good for load balanced / webfarmed apps.

**Comment by silentbobbert** [comment]
Oh yes, you should find the upgrade to 6.1.3 painless. I had no issues on many projects, this is of course no guarantee! :smile:

**Comment by crowinsite** [comment]
Thanks either way. I'm having nuget update all of my projects to 6.1.3 currently. We use Azure currently so Redis should be a big help.
