### ISSUE TITLE
Caching partial data

### ISSUE THREAD

**Issue by giangcoi48k** [silentbobbert/EFCache.Redis#16]
I'm using your EFCache.Redis in my project. It works well! But seem it cache every thing. I just want to cache apart of data, as the data to be frequently accessed. I don't want to cache data storage statistics.
How do I implement that?

**Comment by silentbobbert** [comment]
Hi @giangcoi48k. That's an interesting question!

The EF cache and my redis implementation works at a low level. It looks at the query string and returns you ADO records that get projected to Entities in EF. 

It might be possible to decorate entities with an attribute so they can be ignored, but that should probably be taken care of in the EFCache package and not in the redis implementation. 

You could try having a separate assembly with a separate DbContext just for your storage statistics and not configure caching for it?

**Comment by berniezhao** [comment]
@giangcoi48k you can create a policy and use that to control which entity needs to be cached.
Something like:
```
public class RedisCachingPolicy : CachingPolicy
{
    public List<string> CachableTables { get; private set; }
  
      protected override bool CanBeCached(ReadOnlyCollection<EntitySetBase> affectedEntitySets, string sql, IEnumerable<KeyValuePair<string, object>> parameters)
    {
        if (InvalidateOnly)
        {
            return false;
        }

        var query = affectedEntitySets.Select(e => e.Table ?? e.Name).Where(tableName => !this.CachableTables.Contains(tableName.ToLower()));
        return !query.Any();
    }
}
```

**Comment by giangcoi48k** [comment]
@berniezhao thank you very much, it work for me!

**Comment by giangcoi48k** [comment]
Hi!
When I use storeprocedure to retrieve data, EFCache not work.
exam: 
-  dbcontext.MyTable.Where(....).TolistAsync() ==> cached
-  dbcontext.MyTable.SqlQuery("my_xotoporoxido").ToListAsync() ==> not cached
How?

**Comment by silentbobbert** [comment]
Does your query get projected/materialized to entities? Do these entities get tracked by the EF DbContext change tracker?
I have a feeling SqlQuery bypasses some/most of EF and executes directly?

**Comment by giangcoi48k** [comment]
my table:
```
CREATE TABLE [dbo].[site_menu](
	[Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[parent_id] [int] NULL,
	[href] [nvarchar](50) NULL,
	[a_class] [nvarchar](50) NULL,
	[i_class] [varchar](50) NULL,
	[span_class] [varchar](50) NULL,
	[b_class] [varchar](50) NULL,
	[menu_text] [varchar](50) NULL,
	[ord] [int] NOT NULL,
	[int_level] [int] NULL,
	[string_level] [varchar](50) NOT NULL
)
```
Procedure:
```
;WITH tmp as(
		SELECT Id, parent_id, href, a_class, i_class, span_class, b_class, menu_text, ord,
		CAST(1 AS INT) AS int_level,
		CAST(RIGHT('0000' + CAST(ord AS VARCHAR(3)), 5) AS VARCHAR(50)) AS string_level
		FROM site_menu WHERE parent_id IS NULL
		UNION ALL
		SELECT t2.Id, t2.parent_id, t2.href, t2.a_class, t2.i_class, t2.span_class, t2.b_class, t2.menu_text, t2.ord,
		t1.int_level + 1 AS int_level,
		CAST(t1.string_level + RIGHT('0000' + CAST(t2.ord AS VARCHAR(3)), 5) AS VARCHAR(50)) AS string_level
		FROM tmp t1 INNER JOIN site_menu t2 ON t1.Id = t2.parent_id
	)
	SELECT *
	FROM tmp
	ORDER BY string_level
```

**Comment by berniezhao** [comment]
I don't think sp maps to any entity that's why it's not cached. 
The EF cache is a entity query based cache.  If you look at the Redis you will see the key as entity set.  I don't think it would work for stored procedures...
