### ISSUE TITLE
retry's for azure transient errors

### ISSUE THREAD

**Issue by canberranet** [silentbobbert/EFCache.Redis#17]
I've added some basic retry logic as I am using an azure redis instance and am seeing redis timeouts usually only two or less every 24 hours.  I haven't yet implemented a transient error detection strategy or or wait strategy.  Can anyone see any major problem with the basic operation of this implementation:

public bool GetItem(string key, out object value)
        {
            if (key == null)
            {
                throw new ArgumentNullException("key");
            }
            _database = _redis.GetDatabase();//connect only if arguments are valid to optimize resources 

            key = HashKey(key);
            var now = DateTimeOffset.Now;//local variables are thread safe should be out of sync lock
            int currentRetry = 0;

            for (; ; )
            {
                try
                {
                    // Calling external service.
                    value = _database.Get<CacheEntry>(key);

                    // Return or break.
                    break;
                }
                catch (Exception ex)
                {
                    //Trace.TraceError("Operation Exception");

                    currentRetry++;

                    // Check if the exception thrown was a transient exception
                    // based on the logic in the error detection strategy.
                    // Determine whether to retry the operation, as well as how 
                    // long to wait, based on the retry strategy.
                    if (currentRetry > retryCount)
                    {
                        // If this is not a transient error 
                        // or we should not retry re-throw the exception. 
                        value = null;
                        OnCachingFailed(ex);
                    }
                }

                // Wait to retry the operation.
                // Consider calculating an exponential delay here and 
                // using a strategy best suited for the operation and fault.
                Thread.Sleep(200);
            }
            if (value == null) return false;

            var entry = (CacheEntry)value;

            if (EntryExpired(entry, now))
            {
                InvalidateItem(key);
                value = null;
            }
            else
            {
                entry.LastAccess = now;
                value = entry.Value;
                return true;
            }

            return false;
        }

**Comment by tiwariarvin** [comment]
Hi canberranet - 
Redis is actually single threaded and latency can cause your commands to timeout, below link has an appropriate documentation for the same.

http://redis.io/topics/latency

You may choose to scale to multiple cache nodes if you think your commands are already optimized. Additionally, you may configure redis timeout in it's config if needed like this -

# Close the connection after a client is idle for N seconds (0 to disable)
timeout 1200

Hope this helps.

~Arvin

**Comment by canberranet** [comment]
thanks for the info, I'll look into it.  I've only had two timeouts in over a week now.  I thought it might be caused by azure transient network issues.  We have used the transient fault handling application block for some applications, the SqlAzureExecutionStrategy built into entity framework and the retry strategy for Azure storage.  MS also recommends using it for managed cache and service bus, so the same would apply to redis?  I've gone ahead and added this into RedisCache.cs and after simulating a faulty network the retries are working (not in production yet).  I'm just not sure where, from an architecture perspective this retry logic should go or how it might be passed into RedisCache for situations where it is desired.  
I guess it really belongs in the redis client itself not in this package.

**Comment by silentbobbert** [comment]
Thanks Guys. This is interesting. I think one goal of caching (maybe set by policy) is to fail gracefully. If for any reason the cache doesn't respond or respond within a desired time frame, it should be considered as a cache miss and go to the underlying storage, in this case SQL DB.

The risk here is that the cache will be bypassed and could get out of sync. Perhaps an Optimistic Concurrency Check (OCC) could be used and invalidate cached items once the transient issue goes away?
