### ISSUE TITLE
SlidingExpiration does not work

### ISSUE THREAD

**Issue by HubertoKusters** [silentbobbert/EFCache.Redis#21]
Hi,

Sliding Expiration does not work correctly. When setting this value to 1 minute one would expect that no query would reach the database when constantly refreshing the application (retrieving the record). However, after 1 minute the query is fired again against the database. 
The problem provably has to do with the fact that the LastAccess value of the CacheEntry class is not written back to Redis (see line 107 in RedisCache.cs). So, next time the entry is retrieved from Redis, we get the old LastAccess DateTimeOffset.

Can you confirm that this is the case?

TIA

**Comment by silentbobbert** [comment]
Hi Huberto

I have taken your change and updated the nuget package. 

Many thanks
Ian
