### ISSUE TITLE
Timeout Issues With large datasets...

### ISSUE THREAD

**Issue by bloomk** [silentbobbert/EFCache.Redis#23]
I seem to be having a lot of timeout issues that seem to be caused by somewhat large datasets...

**Comment by silentbobbert** [comment]
Thanks, I feel you might have answered your own question! 

For information, Redis still has limits on what it can do the same as any system (CAP Theory). This package is just a wrapper around two other utilities - one is a base implementation of EF caching (which this project inherits and provides a Redis implementation for) and the other is StackExchange's Redis client who make it super easy to interact with Redis. 

From what you say it sounds like you might need to partition your data across more than one redis instance, and use the multiplexing features to connect to a bunch of redis servers concurrently. This might reduce the pressure on Redis and it might cope with your data volumes more successfully.

Of course you may have found a performance problem with my actual package - I suspect this isn't the case though. Please feel free to provide more details if you do believe something could be improved.

Thanks
Ian

**Comment by bloomk** [comment]
IS there a way to tell it not to cache a specific query? Something Like:

var db = new Data.EVDataContext();
 var Characters = db.Characters
                .Include(c => c.Statements)
                .Include(c => c.UserAccount)
                .Include(c => c.CharacterCars.Select(cc => cc.Car).Select(dd => dd.Parts))
                .Include(c => c.CarTimes)
                .ToNoCacheList();

**Comment by bloomk** [comment]
actually, i found NotCached() .. so disregard that... But is there a way to have it so that it degrades gracefully if the cache times out? So that it does not effect the app?

**Comment by tiwariarvin** [comment]
CachingFailed should help

`public event EventHandler<RedisCacheException> CachingFailed;`
`protected virtual void OnCachingFailed(Exception e, [CallerMemberName] string memberName = "")`
`        {`
`            var handler = CachingFailed;`
`            //don't simply digest, let caller handle exception if no handler provided`
`            if (handler == null)`
`            {`
`                throw new RedisCacheException("Redis | Caching failed for " + memberName, e);`
`            }`
`            var redisCacheException = new RedisCacheException("Caching failed for " + memberName, e);`
`            handler(this, redisCacheException);`
`}`

Additionally, you can override EFCache.CachingPolicy to specify what not to cache. Even this can help you attach a config where you can provide a list entities of what not to cache as I did in my project.
