### ISSUE TITLE
Object Reference not set?

### ISSUE THREAD

**Issue by bloomk** [silentbobbert/EFCache.Redis#24]
Should this be throwing an "Object reference not set to an instance of an object." error? 

[NullReferenceException: Object reference not set to an instance of an object.]
   StackExchange.Redis.ServerEndPoint.get_LastException() +55
   StackExchange.Redis.ExceptionFactory.GetServerSnapshotInnerExceptions(ServerEndPoint[] serverSnapshot) +61
   StackExchange.Redis.ExceptionFactory.NoConnectionAvailable(Boolean includeDetail, RedisCommand command, Message message, ServerEndPoint server, ServerEndPoint[] serverSnapshot) +107
   StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl(Message message, ResultProcessor`1 processor, ServerEndPoint server) +1789
   StackExchange.Redis.RedisBase.ExecuteSync(Message message, ResultProcessor`1 processor, ServerEndPoint server) +75
   StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) +148
   EFCache.Redis.StackExchangeRedisExtensions.Get(IDatabase cache, String key) +87
   EFCache.Redis.RedisCache.GetItem(String key, Object& value) +194

[RedisCacheException: Redis | Caching failed for GetItem]
   EFCache.Redis.RedisCache.OnCachingFailed(Exception e, String memberName) +159
   EFCache.Redis.RedisCache.GetItem(String key, Object& value) +230
   EFCache.CacheTransactionHandler.GetItem(DbTransaction transaction, String key, Object& value) +21
   EFCache.CachingCommand.ExecuteDbDataReader(CommandBehavior behavior) +253
   System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior) +12
   System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c) +9
   System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) +72
   System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext) +356
   System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior) +166
   System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior) +12
   System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior) +37

**Comment by silentbobbert** [comment]
[NullReferenceException: Object reference not set to an instance of an object.]
StackExchange.Redis.ServerEndPoint.get_LastException() +55

Looks like the exception is coming from StackExchange's redis client

StackExchange.Redis.ExceptionFactory.NoConnectionAvailable

Sounds also like you have problems with your redis instance.

What are you using for your redis instance/cluster?
