### ISSUE TITLE
Local locking?

### ISSUE THREAD

**Issue by ocdi** [silentbobbert/EFCache.Redis#25]
Hello, I'm using EFCache.Redis. This is great, however I been observing occasionally that some of the web servers using the cache is deadlocking the entire process. There are multiple threads trying to use GetItem and PutItem. A single thread is calling InvalidateItem and in the stack it is deserializing the CacheEntry. This cache entry is clearly large because I managed to observe a single CPU thread using 100% utilisation and once the deserialization completed all other cores fired up and the pending requests completed.

Is there a reason that locking is required when dealing with the redis database?

Is there a way to do the deserialisation outside of the locking thread to prevent these pauses?

The caching policy doesn't seem to give an option to limit the size of data in the cache - only based on the query and data sets. Unfortunately I don't know what query is generating the massive cache result.

**Comment by ocdi** [comment]
This is the call stack from a memory dump I took of the seemingly locked w3wp process. My theory is that the Deserialize here is taking time. Hard to be sure without measuring this.

```
EFCache.Redis.dll!EFCache.Redis.StackExchangeRedisExtensions.Deserialize<EFCache.Redis.CacheEntry>	Normal
mscorlib.dll!System.Runtime.Serialization.ObjectManager.FindObjectHolder(long objectID)	 
mscorlib.dll!System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(System.Runtime.Serialization.ObjectHolder holder)	 
mscorlib.dll!System.Runtime.Serialization.ObjectManager.RegisterObject(object obj, long objectID, System.Runtime.Serialization.SerializationInfo info, long idOfContainingObj, System.Reflection.MemberInfo member, int[] arrayIndex)	 
mscorlib.dll!System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(object obj, System.Runtime.Serialization.Formatters.Binary.ParseRecord pr, System.Runtime.Serialization.Formatters.Binary.ParseRecord objectPr, bool bIsString)	 
mscorlib.dll!System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(System.Runtime.Serialization.Formatters.Binary.ParseRecord pr)	 
mscorlib.dll!System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()	 
mscorlib.dll!System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser serParser, bool fCheck, bool isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage)	 
mscorlib.dll!System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, bool fCheck, bool isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage)	 
mscorlib.dll!System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, bool fCheck, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage)	 
EFCache.Redis.dll!EFCache.Redis.StackExchangeRedisExtensions.Deserialize<EFCache.Redis.CacheEntry>(byte[] stream)	 
EFCache.Redis.dll!EFCache.Redis.StackExchangeRedisExtensions.Get<EFCache.Redis.CacheEntry>(StackExchange.Redis.IDatabase cache, string key)	 
EFCache.Redis.dll!EFCache.Redis.RedisCache.InvalidateItem(string key)	 
EFCache.Redis.dll!EFCache.Redis.RedisCache.InvalidateSets(System.Collections.Generic.IEnumerable<string> entitySets)	 
EFCache.dll!EFCache.CacheTransactionHandler.Committed(System.Data.Common.DbTransaction transaction, System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext interceptionContext)	 
EntityFramework.dll!System.Data.Entity.Infrastructure.Interception.InternalDispatcher<System.Data.Entity.Infrastructure.Interception.IDbTransactionInterceptor>.Dispatch<System.Data.Common.DbTransaction, System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext>(System.Data.Common.DbTransaction target, System.Action<System.Data.Common.DbTransaction, System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext> operation, System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext interceptionContext, System.Action<System.Data.Entity.Infrastructure.Interception.IDbTransactionInterceptor, System.Data.Common.DbTransaction, System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext> executing, System.Action<System.Data.Entity.Infrastructure.Interception.IDbTransactionInterceptor, System.Data.Common.DbTransaction, System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext> executed)	 
EntityFramework.dll!System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Commit(System.Data.Common.DbTransaction transaction, System.Data.Entity.Infrastructure.Interception.DbInterceptionContext interceptionContext)	 
EntityFramework.dll!System.Data.Entity.Core.EntityClient.EntityTransaction.Commit()	 
```

**Comment by tiwariarvin** [comment]
Is there a reason that locking is required when dealing with the redis database?

Locking it necessary to keep operations atomic, though there is cope to reduce it to transaction scope. I should be taking this up this month to check possibilities. 

Is there a way to do the deserialisation outside of the locking thread to prevent these pauses?

Will check, though will be able to contribute only by mid Jul.

You may run SLOWLOG on your Redis to see what was heavy. Below should give you top 100 heavy commands. 

SLOWLOG Get 100

This should also give you the "key" which you can then query to see how much heavy it was and then use "CashingPolicy" to strict caching if that works for you.

**Comment by ocdi** [comment]
Thanks for your reply. I added a lock timeout to the GetItem and PutItem methods with the help of a colleague. This seems to prevent the lock ups. In this case we treat the DB as unavailable and just fall back to using SQL queries on the server rather than using the cache. I will create a pull request for these tweaks if that is helpful. I think it is only an issue for InvalidateItem dealing with many data sets that combined takes a number of seconds to process, with a large result set (perhaps). Our application was under high load recently which exposed these issues, and some queries can deal with lots of data.

**Comment by tiwariarvin** [comment]
Thanks though when doing this please cross check if cache is in sync with DB; otherwise you will end up having stale data next time.

**Comment by tiwariarvin** [comment]
thanks @ocdi, your changes look safe as a failed put won't affect data consistency and same applies to last visit entry.

**Comment by infogulch** [comment]
`private readonly object _lock = new object();//used to put instance level lock; only one thread will execute code block per instance`

This is ok for a single application, but at best instance-level locks give a false sense of security when there are multiple instances of the application.

It seems `_database` should be a [local variable not a class variable](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Basics.md#using-a-redis-database):

> The object returned from GetDatabase is a cheap pass-thru object, and does not need to be stored.

If this were a local variable that would make the application itself not need a lock. (Note: this variable is vulnerable to race conditions right now because of this.)

If the goal is to make changes atomic, shouldn't we be using [Transactions](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Transactions.md#transactions-in-redis) instead?

**Comment by silentbobbert** [comment]
@tiwariarvin @infogulch I do not currently use my own package to the scale required to experience the issue reported here. The pull request looks like a good & safe modification. I am nervous about pulling it after reading the last comment from @infogulch. I think its safe to accept the request as most consumers of the package probably are happy with the way it works now, and this doesnt seem to change those fundamental characteristics. I am not sure Transactions are the way to go or are even possible with Redis?

@tiwariarvin you are probably the most currently active contributor right now, and seem to have a deeper working knowledge of the inner workings of Redis than me. What do you make of the PR and the ideas raised by @infogulch ?

**Comment by infogulch** [comment]
> I am not sure Transactions are the way to go or are even possible with Redis?

We're using [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Basics.md) for the redis layer. That project appears to have great documentation on how to use it. Note: My first comment linked to their documentation on how transactions can work on redis. 😄

**Comment by ocdi** [comment]
I have experienced some issues with the second level caching as it stands with some queries not being invalidated correctly. This is running with my pull request, so it is either that or something more subtle going on with my application's workload. I've currently got most queries being cached by default (including ones with large results sets and frequently changing), but I am thinking to only cache the EntitySets that don't change very often and are frequently queried (like the user details tables). This might reduce the need and occurrences of my original problem.

**Comment by silentbobbert** [comment]
No discussion on this issue for a year. If this is still a problem, please open a new issue, or better, submit a PR.
