### ISSUE TITLE
RedisCacheException not serializable

### ISSUE THREAD

**Issue by berniezhao** [silentbobbert/EFCache.Redis#27]
Minor issue.  when calling EFCache.Redis from some tools like Update-Database script, if redis server is not accessible it generates the below error instead of the actual exception message.  It would be cool to mark RedisCacheException serializable so it can always show meaningful errors.

```
System.Runtime.Serialization.SerializationException: Type 'EFCache.Redis.RedisCacheException' in assembly 'EFCache.Redis, Version=2016.5.24.1, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
```

**Comment by silentbobbert** [comment]
Thanks for flagging that up.
[Commit with suggestion implemented](https://github.com/silentbobbert/EFCache.Redis/commit/7659640725fb7c5911b6a468311690e157a5b773)

It will make the next release 👍
