### ISSUE TITLE
how to use it without DbConfiguration

### ISSUE THREAD

**Issue by qinshimignyue** [silentbobbert/EFCache.Redis#28]
I use EF with IOC,I can not use DbConfiguration
builder.RegisterType<PermissionEntities>().As<DbContext>().WithParameter( (p, c) => string.Equals(p.Name, "existingConnection"), (p, c) => { return GetDbConnection(); }). InstancePerRequest();

**Comment by silentbobbert** [comment]
There is no other way to intercept the communications, you have to use DbConfiguration. It works just fine with Unity IoC with no special setup, just plain interface to context mapping and per request is the default scope.

**Comment by qinshimignyue** [comment]
It works just fine with Unity IoC with no special setup..........
NO,can you????

**Comment by qinshimignyue** [comment]
http://images2015.cnblogs.com/blog/83201/201703/83201-20170329141639248-791988636.png
if I write to config file

**Comment by qinshimignyue** [comment]
thank you sir,  'some place called first '
two other question : 
1.can Distributed System   share the same Key?
2.when the application retart ,can  the same query share last cached data?
3.does this framework cache every query?

**Comment by silentbobbert** [comment]
To answer some of your questions:

It DOES work with Unity IoC with no special setup. A basic binding works fine. This is how I use it in my own projects.

1.can Distributed System share the same Key?
Other applications/services or instances of the same app if load balanced can share this redis cache and make use of (or update) the cached records.

2.when the application retart ,can the same query share last cached data?
Yes. This is one of the main reasons for using Redis. It is "out of process" so it is not tied to the life time of your app/website. They can crash/restart as many times as you like. If the same SQL query (which becomes the key) is generated by ANY instance of ANY app, as long as the entity has not expired in your cache, the data will be re-used.

3.does this framework cache every query?
By default, yes.
