### ISSUE TITLE
Get and then Sets

### ISSUE THREAD

**Issue by vkctata** [silentbobbert/EFCache.Redis#31]
Hi 

We implemented this package in out application and whenever we try to get data. It first gets and then sets the same key. Is this normal?

Thanks
Ven

**Comment by silentbobbert** [comment]
Ven

The redis key is either the SQL query string used to fetch your data, or if
the query string is large,  for performance reasons, the SQL string is
hashed instead, and the hash is used as the key.

If your application generates the same SQL you should get a cache hit.

When you get a hit, the results that were previously obtained by your query
that are stored in redis are returned. If the results are old, they could
be discarded and new results fetched from the DB instead. You control how
old your data is allowed to be by using a custom Caching Policy class,
inheriting from the base class but overriding the default values with
sliding and absolute expiry times to suit your use case.

Does that help?

Cheers
Ian

**Comment by vkctata** [comment]
thanks for your reply. It cleared my initial doubt.  

Can I know why we are using locks on sets to Redis?

Is it possible to add async implementations for gets and sets?

**Comment by silentbobbert** [comment]
The locks add thread safety, to make sure gets/sets are consistent/atomic.

It might be possible to add async methods, if the StackExchange Redis package which is used to handle Redis operations offer async methods.

I am quite happy to take PRs if you feel this is worth doing.

Thanks
Ian

**Comment by vkctata** [comment]
thanks for your reply. 

We pulled your code and made some changes. we don't require thread safety for our application. So, we removed locks. 

Instead of storing a CacheEntry object as value. we made changes to store value and call  _database.KeyExpire(key, _slidingTimeout, CommandFlags.FireAndForget); which will increase the expiry time on keys. 
**This increase our perfomance by 40%.** 
 
 The full implementation below. 

`using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;

namespace EFCache.Redis
{
    // ReSharper disable once ClassWithVirtualMembersNeverInherited.Global
    public class RedisCache : IRedisCache
    {
        //Note- modifying these objects will alter locking scheme
        private readonly object _lock = new object();//used to put instance level lock; only one thread will execute code block per instance

        private IDatabase _database;//lock don't work on this because it is being reassigned each time new connection requested; though _redis.GetDatabase() is thread safe and should be used to let mutiplexor manage connection for best performance. Considering these let's avoid putting lock on it
        private readonly ConnectionMultiplexer _redis;
        private readonly string _cacheIdentifier;
        public event EventHandler<RedisCacheException> CachingFailed;
        private TimeSpan _slidingTimeout = new TimeSpan(0, 0, 30);

        public RedisCache(string config) : this(ConfigurationOptions.Parse(config)) { }

        // ReSharper disable once MemberCanBePrivate.Global
        public RedisCache(ConfigurationOptions options)
        {
            _redis = ConnectionMultiplexer.Connect(options);
            _cacheIdentifier = "__EFCache.Redis_EntitySetKey_";
        }

        public RedisCache(string config, string cacheIdentifier)
        {
            _redis = ConnectionMultiplexer.Connect(ConfigurationOptions.Parse(config));
            _cacheIdentifier = cacheIdentifier;
        }

        public RedisCache(ConfigurationOptions options, string cacheIdentifier)
        {
            _redis = ConnectionMultiplexer.Connect(options);
            _cacheIdentifier = cacheIdentifier;
        }

        protected virtual void OnCachingFailed(Exception e, [CallerMemberName] string memberName = "")
        {
            var handler = CachingFailed;
            //don't simply digest, let caller handle exception if no handler provided
            if (handler == null)
            {
                throw new RedisCacheException("Redis | Caching failed for " + memberName, e);
            }
            var redisCacheException = new RedisCacheException("Caching failed for " + memberName, e);
            handler(this, redisCacheException);
        }

        /// <summary>
        /// get item from redis
        /// </summary>
        /// <param name="key"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public bool GetItem(string key, out object value)
        {
            key.GuardAgainstNullOrEmpty(nameof(key));
            _database = _redis.GetDatabase();//connect only if arguments are valid to optimize resources 
            key = HashKey(key);
            try
            {
                value = _database.Get<object>(key);
            }
            catch (Exception e)
            {
                value = null;
                OnCachingFailed(e);
            }

            if (value == null) return false;

            try
            {
                _database.KeyExpire(key, _slidingTimeout, CommandFlags.FireAndForget);
            }
            catch (Exception e)
            {
                // Eventhough an error has occured, we will return true, because the retrieval of the entity was a success
                OnCachingFailed(e);
            }
            return true;
        }

        private static bool EntryExpired(CacheEntry entry, DateTimeOffset now) => entry.AbsoluteExpiration < now || (now - entry.LastAccess) > entry.SlidingExpiration;

        public void PutItem(string key, object value, IEnumerable<string> dependentEntitySets, TimeSpan slidingExpiration, DateTimeOffset absoluteExpiration)
        {
            key.GuardAgainstNullOrEmpty(nameof(key));
            _slidingTimeout = slidingExpiration;
            // ReSharper disable once PossibleMultipleEnumeration - the guard clause should not enumerate, its just checking the reference is not null
            dependentEntitySets.GuardAgainstNull(nameof(dependentEntitySets));

            _database = _redis.GetDatabase();

            key = HashKey(key);
            // ReSharper disable once PossibleMultipleEnumeration - the guard clause should not enumerate, its just checking the reference is not null
            var entitySets = dependentEntitySets.ToArray();

            //lock (_lock)
            //{
            try
            {
                foreach (var entitySet in entitySets)
                {
                    _database.SetAdd(AddCacheQualifier(entitySet), key, CommandFlags.FireAndForget);
                }

                _database.Set(key, value);
                _database.KeyExpire(key, _slidingTimeout, CommandFlags.FireAndForget);
            }
            catch (Exception e)
            {
                OnCachingFailed(e);
            }
            //}
        }

        private RedisKey AddCacheQualifier(string entitySet) => string.Concat(_cacheIdentifier, ".", entitySet);

        private static string HashKey(string key)
        {
            //Looking up large Keys in Redis can be expensive (comparing Large Strings), so if keys are large, hash them, otherwise if keys are short just use as-is
            if (key.Length <= 128) return key;
            using (var sha = new SHA1CryptoServiceProvider())
            {
                key = Convert.ToBase64String(sha.ComputeHash(Encoding.UTF8.GetBytes(key)));
                return key;
            }
        }

        public void InvalidateSets(IEnumerable<string> entitySets)
        {
            // ReSharper disable once PossibleMultipleEnumeration - the guard clause should not enumerate, its just checking the reference is not null
            entitySets.GuardAgainstNull(nameof(entitySets));

            _database = _redis.GetDatabase();

            var itemsToInvalidate = new HashSet<string>();

            //lock (_lock)
            //{
            try
            {
                // ReSharper disable once PossibleMultipleEnumeration - the guard clause should not enumerate, its just checking the reference is not null
                foreach (var entitySet in entitySets)
                {
                    var entitySetKey = AddCacheQualifier(entitySet);
                    var keys = _database.SetMembers(entitySetKey).Select(v => v.ToString());
                    itemsToInvalidate.UnionWith(keys);
                    _database.KeyDelete(entitySetKey, CommandFlags.FireAndForget);
                }
            }
            catch (Exception e)
            {
                OnCachingFailed(e);
                return;
            }

            foreach (var key in itemsToInvalidate)
            {
                InvalidateItem(key);
            }
            //}
        }

        public void InvalidateItem(string key)
        {
            key.GuardAgainstNullOrEmpty(nameof(key));

            _database = _redis.GetDatabase();

            key = HashKey(key);

            lock (_lock)
            {
                try
                {
                    var entry = _database.Get<CacheEntry>(key);

                    if (entry == null) return;

                    _database.KeyDelete(key, CommandFlags.FireAndForget);

                    foreach (var set in entry.EntitySets)
                    {
                        _database.SetRemove(AddCacheQualifier(set), key, CommandFlags.FireAndForget);
                    }
                }
                catch (Exception e)
                {
                    OnCachingFailed(e);
                }
            }
        }
        // ReSharper disable once BuiltInTypeReferenceStyle
        public Int64 Count
        {
            get
            {
                _database = _redis.GetDatabase();
                lock (_lock)
                {
                    var count = _database.Multiplexer.GetEndPoints()
                        .Sum(endpoint => _database.Multiplexer.GetServer(endpoint).Keys(pattern: "*").LongCount());
                    return count;
                }
            }
        }
        public void Purge()
        {
            _database = _redis.GetDatabase();
            lock (_lock)
            {
                foreach (var endPoint in _database.Multiplexer.GetEndPoints())
                {
                    _database.Multiplexer.GetServer(endPoint).FlushDatabase();
                }
            }

        }
    }
}

`
