### ISSUE TITLE
How to Use it in SaaS Model Applications

### ISSUE THREAD

**Issue by indiaweblab** [silentbobbert/EFCache.Redis#38]
Hi, Its great package but may know how to use it SaaS-based applications. Are there any drawbacks of using it SaaS-based applications

**Comment by silentbobbert** [comment]
Hi, the package is designed for use in load balanced scenarios where its important your different instances serving request share a consistent cache. This is well suited to SaaS delivery models. If your current solution is multi-tenant, then using this package should not introduce issues and should respect your partitioning model.
